In [1]:
import torch
import numpy as np

## Indexing, Slicing

In [9]:
x = torch.rand(size=(3,4))
x

tensor([[0.4662, 0.9302, 0.3527, 0.4858],
        [0.4701, 0.0616, 0.0107, 0.8433],
        [0.4257, 0.2782, 0.6458, 0.5032]])

x[row, cols]

row -> start:stop:step

col -> start:stop:step        

In [10]:
x[0,:]

tensor([0.4662, 0.9302, 0.3527, 0.4858])

In [11]:
x[:,0]

tensor([0.4662, 0.4701, 0.4257])

In [14]:
x[0:2, 0:3]

tensor([[0.4662, 0.9302, 0.3527],
        [0.4701, 0.0616, 0.0107]])

In [15]:
x[0:2, 0:3:2]

tensor([[0.4662, 0.3527],
        [0.4701, 0.0107]])

In [16]:
x[0,0]

tensor(0.4662)

In [19]:
x[0,0] = 11

In [20]:
x

tensor([[1.1000e+01, 9.3021e-01, 3.5273e-01, 4.8576e-01],
        [4.7009e-01, 6.1568e-02, 1.0703e-02, 8.4334e-01],
        [4.2567e-01, 2.7815e-01, 6.4583e-01, 5.0318e-01]])

In [21]:
x = torch.rand(size=(3,4))
y = torch.rand(size=(3,4))


## Concatination

In [22]:
torch.cat((x, y), dim=1)

tensor([[0.8759, 0.6237, 0.0273, 0.6163, 0.4174, 0.9742, 0.8510, 0.7403],
        [0.9567, 0.2370, 0.8376, 0.2125, 0.5866, 0.5525, 0.3482, 0.1966],
        [0.1307, 0.5164, 0.8591, 0.0752, 0.0532, 0.3344, 0.0439, 0.7195]])

In [23]:
torch.cat((x, y), dim=0)

tensor([[0.8759, 0.6237, 0.0273, 0.6163],
        [0.9567, 0.2370, 0.8376, 0.2125],
        [0.1307, 0.5164, 0.8591, 0.0752],
        [0.4174, 0.9742, 0.8510, 0.7403],
        [0.5866, 0.5525, 0.3482, 0.1966],
        [0.0532, 0.3344, 0.0439, 0.7195]])

In [24]:
x.shape

torch.Size([3, 4])

## Reshaping

In [25]:
x.reshape(2,6)

tensor([[0.8759, 0.6237, 0.0273, 0.6163, 0.9567, 0.2370],
        [0.8376, 0.2125, 0.1307, 0.5164, 0.8591, 0.0752]])

In [26]:
x.reshape(2,3) # no. of elements should match

RuntimeError: shape '[2, 3]' is invalid for input of size 12

In [27]:
x.reshape(1,12)

tensor([[0.8759, 0.6237, 0.0273, 0.6163, 0.9567, 0.2370, 0.8376, 0.2125, 0.1307,
         0.5164, 0.8591, 0.0752]])

In [28]:
x.reshape(12,1)

tensor([[0.8759],
        [0.6237],
        [0.0273],
        [0.6163],
        [0.9567],
        [0.2370],
        [0.8376],
        [0.2125],
        [0.1307],
        [0.5164],
        [0.8591],
        [0.0752]])

In [31]:
x.shape

torch.Size([3, 4])

In [32]:
x.view(-1) # Flattening

tensor([0.8759, 0.6237, 0.0273, 0.6163, 0.9567, 0.2370, 0.8376, 0.2125, 0.1307,
        0.5164, 0.8591, 0.0752])

In [33]:
x.view(-1).shape # flattening a tensor

torch.Size([12])

In [34]:
# batch flattening ops
batch = 16

torch.rand((batch, 2,5)).view((batch, -1))

tensor([[0.5898, 0.8485, 0.6827, 0.4938, 0.5183, 0.9858, 0.5632, 0.4546, 0.6970,
         0.9603],
        [0.0669, 0.4628, 0.9424, 0.0092, 0.0878, 0.9861, 0.9675, 0.8619, 0.2528,
         0.1191],
        [0.6260, 0.0551, 0.4902, 0.4019, 0.2533, 0.5351, 0.0208, 0.0644, 0.4734,
         0.1473],
        [0.5578, 0.7696, 0.9104, 0.2832, 0.4618, 0.6799, 0.0138, 0.6154, 0.2280,
         0.6078],
        [0.4576, 0.9747, 0.4234, 0.8570, 0.5523, 0.9100, 0.3069, 0.8513, 0.7162,
         0.6048],
        [0.6103, 0.4901, 0.7255, 0.4219, 0.4437, 0.9195, 0.0497, 0.0241, 0.9140,
         0.4657],
        [0.1688, 0.0681, 0.9507, 0.0024, 0.7920, 0.7637, 0.1157, 0.6318, 0.4604,
         0.1113],
        [0.9648, 0.4391, 0.2547, 0.3421, 0.2013, 0.1122, 0.9653, 0.2397, 0.7509,
         0.2061],
        [0.2421, 0.7438, 0.0903, 0.2956, 0.1293, 0.6893, 0.8242, 0.3162, 0.8461,
         0.1161],
        [0.3650, 0.5304, 0.2917, 0.3597, 0.2389, 0.0235, 0.7417, 0.5334, 0.4782,
         0.8095],
        [0